[package]
name = "yong-trans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinyin = "0.10.0"
nom = "7.1.3"
itertools = "0.11.0"
humantime = "2.1.0"
num-bigint = "0.4.4"
chrono = "0.4.31"
